# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
platform :ios, '17.0'

target 'ChatAppSwiftUI' do
  use_frameworks!
  
  pod 'Alamofire'
  pod 'SQLite.swift', '~> 0.12.2'

  target 'ChatAppSwiftUITests' do
    inherit! :search_paths
  end
end
